language: node_js
node_js:
  - "stable"

before_script:
  - cd aviasales/solution

install:
  - npm i

script:
  - npm run lint

cache:
  directories:
    - "aviasales/solution/node_modules"

on:
  branch: master
