language: node_js

node_js: "stable"

install:
  - cd aviasales/solution
  - npm i

# script: npm run lint && npm run build && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
script: npm run lint && npm run build

before_deploy: npm i now --no-save

deploy:
  - provider: script
    script: now --token $NOW_TOKEN --public
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN --public && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true

cache:
  directories:
  - "aviasales/solution/node_modules"

on:
  branch: master
