export const FETCH_TICKETS_REQUEST = '@tickets/FETCH_TICKETS_REQUEST';
export const FETCH_TICKETS_SUCCESS = '@tickets/FETCH_TICKETS_SUCCESS';
export const FETCH_TICKETS_FAILURE = '@tickets/FETCH_TICKETS_FAILURE';
